name: Build Release APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git unzip autoconf libtool pkg-config zlib1g-dev

      # 关键：每次构建强制删除旧构建目录，彻底清除x86 pygame缓存！
      - name: Clean old build cache
        run: |
          rm -rf .buildozer env bin build

      - name: Build APK
        run: |
          python3.10 -m venv env
          source env/bin/activate
          pip install buildozer==1.6.0 cython==0.29.36
          buildozer android debug

      - name: Upload built APK
        uses: actions/upload-artifact@v4
        with:
          name: GameAPK
          path: bin/*.apk
